version: "3"

volumes:
  static:
  database:

services:
  cloud_ky:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DJANGO_ENV: product
    environment:
      DJANGO_ENV: product
    image: cloud_ky
    container_name: cloud_ky
    working_dir: /home/docker/simple_cloud
    volumes:
      - ./logs:/home/docker/simple_cloud/logs
      - ./views:/home/docker/simple_cloud/views
    ports:
      - "11005:8000"
    command: uwsgi --ini uwsgi.ini
    restart: always
